### PR TITLE
Move async API for 3.7 compatibility

### LINKED ISSUE #6: Use of 'async' variable name breaks erequests on 3.7 and later
```
Traceback (most recent call last):
  File "eve.py", line 18, in <module>
    import erequests
  File "/mnt/d/Users/Peter/Desktop/scrape_site/testing/git/eve/venv/lib/python3.7/site-packages/erequests.py", line 101
    async = AsyncRequestFactory
          ^
SyntaxError: invalid syntax
```

> ## What’s New In Python 3.7
> **Backwards incompatible syntax changes:**
> async and await are now reserved keywords.

https://docs.python.org/3/whatsnew/3.7.html

Should be a simple find/replace to fix.

### PR DESCRIPTION
**Pull request by AGSPhoenix**
Fixes #6.

The big block of _async functions feel clunky, but I'm not aware of a more concise representation.

### CODE REVIEW

**Comment by saghul** [comment]
Looking good, thanks! Since I'm no longer using this module myself, would you like to get the commit bit?

**Comment by AGSPhoenix** [comment]
I'm not really sure what you mean by 'the commit bit'.

**Comment by saghul** [comment]
The rights to manage this repository yourself.

**Comment by AGSPhoenix** [comment]
I'm not sure I can commit much time to the module, but I might be able to help with the occasional bug report (though based on the other issues - or lack thereof - it might be a while before that happens). So long as your expectations are suitably low, sure.

**Comment by saghul** [comment]
Absolutely.

**Pull request merged**
